config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :sessions, only: [:new, :create, :destroy]
  get '/login', to: 'sessions#new'
  resources :users, only: [:show, :new, :create, :edit, :update]
  resources :hikes do 
    resources :signups, shallow: true
  end
  resources :locations do 
    resources :hikes, shallow: true
  end
  root 'pages#show', page: 'home'
  get '/pages/:page', to: 'pages#show', as: :page
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :commentable, polymorphic: true
end

app/models/hike.rb
class Hike < ApplicationRecord
  belongs_to :location
  belongs_to :user
  has_many :signups, dependent: :destroy
  has_many :users, through: :signups, dependent: :destroy
end

app/models/location.rb
class Location < ApplicationRecord
    has_many :hikes, dependent: :destroy
    has_attached_file :main_picture, styles: { medium: "500x500>", thumb: "250x250>" }, presence: true
    validates_attachment_content_type :main_picture, content_type: /\Aimage\/.*\z/
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :user
  belongs_to :location
  has_many :comments, as: :commentable, dependent: :destroy
  has_attached_file :image, styles: { medium: "500x500>", thumb: "250x250>" }, presence: true
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/signup.rb
class Signup < ApplicationRecord
  belongs_to :user
  belongs_to :hike
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    validates :email, presence: true, uniqueness: true
    after_initialize :set_defaults
    has_many :created_hikes, foreign_key: "user_id", class_name: "Hike", dependent: :destroy
    has_many :signups, dependent: :destroy
    has_many :hikes, through: :signups, dependent: :destroy
    has_attached_file :profile_picture, styles: { medium: "500x500>", thumb: "250x250>" }, presence: true
    validates_attachment_content_type :profile_picture, content_type: /\Aimage\/.*\z/

    private
    def set_defaults
        self.admin = false if self.admin.nil?
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  def authorize
    redirect_to login_path, alert: 'Not authorized - you must be logged in!' if current_user.nil?
  end
  
  private
  helper_method :current_user

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

end

app/controllers/hikes_controller.rb
class HikesController < ApplicationController
    before_action :authorize, except: [:index, :show]

    def new
        @location = Location.find(params[:location_id])
        @hike = Hike.new
    end

    def show
        @hike = Hike.find(params[:id])
        @users = @hike.users
        @locations = @hike.location

    end

    def edit
        @hike = Hike.find(params[:id])
    end

    def create
        @hike = Hike.new(params.require(:hike).permit(:name, :date))
        @hike.user = current_user
        @loc = Location.find(params[:location_id]).hikes << @hike

        if @hike.save
            redirect_to hikes_path
        else 
            render :new 
        end 

    end

    def update
        @hike = Hike.find(params[:id])
        if @hike.update_attributes(params.require(:hike).permit(:name, :date))
            redirect_to hike_path(@hike)
        else
            render :edit
        end
    end
    
    def index
        @hikes = Hike.all
    end

    def destroy
        @hike = Hike.find(params[:id])
        @hike.destroy
        redirect_to root_path
    end

    private
    def hike_params
        params.require(:hike).permit(user_ids: [])
    end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
    def new
        @location = Location.new
    end

    def show
        @location = Location.find(params[:id])
    end

    def index
        @locations = Location.all
    end
    
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def show
        page = params[:page]
        render "pages/#{params[:page]}"
    end
end 

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

def new
end

def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
    session[:user_id] = user.id
    redirect_to root_path, notice: 'Logged in!'
    else
    flash.now.alert = 'Invalid login credentials - try again!'
    render :new
    end
end

def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "Logged out!"
end

end

app/controllers/signups_controller.rb
class SignupsController < ApplicationController

    def new
        @signup = Signup.find(params[:location_id])
        @hike = Hike.new
    end

    def show
        @signup = Signup.find(params[:id])
    end

    def edit
        @signup = Signup.find(params[:id])
    end

    def create
        signup = Signup.find_by(hike_id: params[:hike_id], user: current_user)
        if signup
            redirect_to hike_path(signup.hike)
        else
            @signup = Signup.new(hike_id: params[:hike_id], user: current_user)
            if @signup.save
                redirect_to hike_path(@signup.hike)
            else 
                render :new 
            end 
        end
    end

    def update
        @signup = Signup.find(params[:id])
        if @signup.update_attributes(params.require(:signup).permit(:hike_id, :user_id))
            redirect_to hike_path(@signup.hike)
        else
            render :edit
        end
    end
    
    def index
        @signup = Signups.all
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        @user = User.new
    end

    def show
        @user = User.find(params[:id])
    end

    def edit
        @user = User.find(params[:id])
    end

    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
        flash[:notice] = "You have successfully signed up!"
        redirect_to user_path(@user.id)
        else
        redirect_to new_user_path
        end
    end
    
    def index
        @user = User.all
    end

    def destroy
        @user = User.find(params[:id])
        @user.destroy
        respond_to do |format|
        flash[:success] = "User deleted."
        format.html { redirect_to user_path }
        end
    end

    def update
        @user = User.find(params[:id])
        if @user.update_attributes(params.require(:user).permit(:name, :email, :password_digest, :hometown, :level, :contact, :facebook_url, :instagram_url, :profile_picture))
            redirect_to user_path(@user)
        else
            render :edit
        end
    end

    private
    def user_params
        params.require(:user).permit(:name, :email, :password_digest, :hometown, :level, :contact, :facebook_url, :instagram_url, :profile_picture)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/hikes/edit.html.erb
<h3 class="text-center">Update <%= link_to @hike.name, hike_path(@hike.id) %> details here! </h3>

        <%= form_for [@user, @location, @hike] do |f| %>
        <div class="col-sm-4 col-sm-offset-2">
            <%= f.label :name, "Name of Your Hike:" %>
            <%= f.text_field :name %>
            <br/>
            <br/>
            <%= f.label :date, "When are we hiking?" %>
            <%= f.date_field :date %>
        </div>
        <div id="submit-new" class="col-sm-4 col-sm-offset-2">
            <%= f.submit "Update Your Hike" %>
        </div>
        <% end %>
    </div>

app/views/hikes/index.html.erb
<h2 class="text-center">Upcoming Hikes</h2>

<div class="hike_info">
<ul>
	<% @hikes.each do |h| %>
		<br/>
		<div class="col-sm-12 col-sm-offset-1">
			<h4>Hike Name: <%= link_to h.name, hike_path(h.id) %></h4></li>
		</div>
    	<div class="col-sm-3 col-sm-offset-1">
			<li>Date of Hike: <p><%= h.date %></p></li>
		</div>
    	<div class="col-sm-4">
			<li>Host: <p><%= link_to h.user.name, user_path(h.user) %></p></li>
			<li>Location: <p><%= link_to h.location.location_name, location_path(h.location) %></p></li>
		</div>
    	<div class="col-sm-3 col-sm-offset--1">
			<li>Hike Length: <p><%= h.location.length %></p></li>
			<li>Hike Difficulty: <p><%= h.location.level %></p></li>
		</div>
		<br/>
		<br/>
	<% end %>
</ul>
</div>

app/views/hikes/new.html.erb
<h3 class="text-center">Create A New Hike!</h3>

    <%= form_for [@user, @location, @hike] do |f| %>
        <div class="col-sm-4 col-sm-offset-2">
            <%= f.label :name, "Name of Your Hike:" %>
            <%= f.text_field :name %>
            <br/>
            <br/>
            <%= f.label :date, "When are we hiking?" %>
            <%= f.date_field :date %>
        </div>
        <div id="submit-new" class="col-sm-4 col-sm-offset-2">
            <%= f.submit "Save New Hike" %>
        </div>
        <% end %>
    </div>

app/views/hikes/show.html.erb
<h3 class="text-center">Upcoming Hike: <%= link_to @hike.name, hike_path(@hike.id) %></h3>
<br/>
<br/>

<div class="row">
    <div class="col-sm-5 col-sm-offset-1">
        <div class="row">
            <div class="col-sm-4 my-labels">
                <p>Date of hike:  </p>
                <p>Length of hike:  </p>
                <p>Difficulty level: </p>
                <p>Hike organizer: </p>
                <p>Hike location: </p>
            </div>
            <div class="col-sm-6">
                <p><%= @hike.date %> </p>
                <p><%= @hike.location.length %> </p>
                <p><%=@hike.location.level %> </p>
                <p><%= link_to @hike.user.name, user_path(@hike.user)%></p></li>
                <p><%= link_to @hike.location.location_name, location_path(@hike.location)%></p>
            </div>
        </div>
    </div>
    <div class="col-sm-5" id="right-col">
        <p><img src="<%=@hike.location.main_picture%>" > </p>
        
    </div>
</div>
<hr>
<div class="row">
	<div class="col-sm-5 col-sm-offset-1 text-center">
            <p class="label-color">Hikers Attending:</p>
            <ul> 
                <% @users.each do |user|%>
                    <li><%= link_to user.name, user_path(user) %></li> 
                <% end %>
            </ul>
    </div>
	<div class="col-sm-5 edit_links text-center">
        <% unless current_user.hikes.exists?(@hike.id) %>
            <p><%= link_to("Join This Hike", hike_signups_path(@hike), method: :post) %></p>
        <% end %>
        <p> <%= link_to "Edit Your Hike", edit_hike_path(@hike) %></p>
        <p> <%= link_to "Cancel Your Hike", hike_path(@hike), 
                                                    :data => {  :confirm=> "You sure?!?!", 
                                                                :method => "delete"} %></p>
    </div>
</div>                                                                

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hiking With Friends</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Poppins" rel="stylesheet">
  </head>
    <div="top">
      <% if current_user %>
        Welcome, <%= current_user.name %>
          &nbsp;&nbsp;|&nbsp;&nbsp;
          <%= link_to 'My Profile', user_path(current_user)%>
          &nbsp;&nbsp;|&nbsp;&nbsp;
          <%= link_to 'Log Out', session_path('dummy'), method: :delete %>
          <% else %>
          &nbsp;&nbsp;
          <%= link_to 'Log In', login_path %>
          &nbsp;&nbsp;|&nbsp;&nbsp;
          <%= link_to 'Sign Up', new_user_path %>
      <% end %>
      </div>
  <body>
    <%= yield %>
  <br/>
  <br/>
  <div id="bottom_nav">
    <p role="home"> <%= link_to "Home", page_path(:home) %></p>
      &nbsp;&nbsp;|&nbsp;&nbsp;
    <p role="about"><%= link_to "About HWF", '/pages/about' %></p>
          &nbsp;&nbsp;|&nbsp;&nbsp;
    <p role="hikes"><%= link_to "Upcoming Hikes", '/hikes' %></p>
  </div>
  </body>
</html>

app/views/locations/index.html.erb
<h2 class="text-center">Hiking Locations</h2>

	<% @locations.each do |l| %>
	<ul>
	    <div class="row">
			<div id="city_photo" class="col-sm-3 col-sm-offset-1">
				<li class="label-color">Name: <p><%= link_to l.location_name, location_path(l.id) %></p></li>
				<%= image_tag l.main_picture.url, id: "main_picture", class: "img-thumbnail" %>
			</div>
			<div class="col-sm-3 col-sm-offset-1">
				<br/>
				<br/>
				<li class="label-color">Address: <p><%= l.location_address %></p></li>
				<li class="label-color">Nearest City: <p><%= l.nearest_city %></p></li>
				<li class="label-color">State: <p><%= l.state %></p></li>
			</div>
			<div class="col-sm-3 col-sm-offset-1">
				<br/>
				<br/>
				<li class="label-color">Hike length: <p><%= l.length %></p></li>
				<li class="label-color">Hike difficulty: <p><%= l.level %></p></li>
			</div>
		</div>
	</ul>	
<% end %>

app/views/locations/new.html.erb
<% provide(:title, "Create New Location") %>
<h4>Know a great hiking trail? Share it here with the group!</h4>

<%= form_for(@location) do |f| %>
    <div>
        <%= f.label :location_name, "Trail's name:" %>
        <%= f.text_field :location_name %>
    </div>
    <div>
        <%= f.label :location_address, "Trail's address:" %>
        <%= f.text_field :location_address %>
    </div>
    <div>
        <%= f.label :nearest_city, "Closest big city:" %>
        <%= f.text_field :nearest_city %>
    </div>
    <div>
        <%= f.label :state, "State:" %>
        <%= f.text_field :state %>
    </div>
    <div>
        <%= f.label :level, "Trail's difficulty level:" %>
        <%= f.select(:level) do %>
            <% [['Novice', "Novice"], ['Intermediate', "Intermediate"], ['Expert', "Expert"], ['Sherpa', "Sherpa"]].each do |c| -%>
                <%= content_tag(:option, c.first, value: c.last) %>
            <% end %>
        <% end %>
    </div>
    <div> 
        <%= f.label :length, "Trail's length (indicate miles or km):" %>
        <%= f.text_field :length %>
    </div>
    <div>
        <%= f.label :google_map_link, "Google map link:" %>
        <%= f.url_field :google_map_link, :value => "http://<fill in the rest>" %>
    </div>
    <div>
        <%= f.label :main_picture, "Picture of the trail:" %>
        <%= f.file_field :main_picture %><br><br>
</ul>

<%= f.submit 'Create Trail!' %>

<% end %>

app/views/locations/show.html.erb
<h2 class="text-center">All about <%= link_to @location.location_name, location_path(@location.id) %>! </h2>

<div id="row">
    <div class="col-sm-12 text-center">
    <h4> <%= link_to "Create a New Hike", new_location_hike_path(@location) %></h4>
    </div>
</div>

<div id="row">
    <div id="city_photo" class="col-sm-5 col-sm-offset-1">
        <%= image_tag @location.main_picture.url %>
        <p class="label-color">Nearest big city:</p>  <p><%= @location.nearest_city %></p>
    </div>
<div>

<div class="row">
    <div class="col-sm-5">
            <div class="col-sm-4 my-labels">
            <p>Difficulty: </p>
            <p>Length: </p>
            <p>Map: </p>
            <p>Address: </p>
            </div>
    <div class="col-sm-6 col-sm-offset-1">
        <p><%= @location.level%> </p>
        <p><%= @location.length%> </p>
        <p><%= link_to "Google Map", "#{@location.google_map_link}" %> </p> 
        <p><%= @location.location_address %> </p>
    </div> 
</div>

<div class="row">
    <div class="col-sm-6 col-sm-offset-1">
        <p>Upcoming Hikes here: </p>
        <% @location.hikes.each do |hike| %>
        <li><%= link_to hike.name, hike_path(hike) %></li>
        <% end %>
    </div>
</div>

app/views/pages/about.html.erb
<h2>Hiking With Friends</h2>

<p>Hiking with Friends is a site where users can look to find other like-minded individuals to get out in nature.

app/views/pages/home.html.erb
    <div class="center jumbotron" style="background-color: #8FC1E3;">
        <h2>HIKING WITH FRIENDS</h2>
        <p>allowing people to get out in nature with other like-minded hikers</p>
        </div>

        <div id="welcome_img"></div>

        <div class="link_container">
        <%= link_to "Hike Locations", locations_path %>
        </div>

app/views/users/destroy.html.erb
link_to user_path

app/views/users/edit.html.erb
<section id="hikes">
<h2 class="text-center">Update your profile!</h2>

<%= form_for(@user) do |f| %>
<div class="row">
        <div class="col-sm-3 col-sm-offset-1">
            <%= f.label :name, "Hiker's name:" %>
            <%= f.text_field :name %>
        </div>

        <div class="col-sm-3 col-sm-offset-1">
            <%= f.label :email, "Hiker's e-mail address:" %>
            <%= f.email_field :email %>
        </div>

        <div class="col-sm-3 col-sm-offset-1">
            <%= f.label :hometown, "Hiker's hometown:" %>
            <%= f.text_field :hometown %>
        </div>
</div>
<div class="row">
        <div class="col-sm-3 col-sm-offset-1">
            <%= f.label :password_digest, "Hiker's password:" %>
            <%= f.password_field :password_digest %>
        </div>
 
        <div class="col-sm-3 col-sm-offset-1">
            <%= f.label :level, "Hiker's ability level:" %>
            <%= f.select(:level) do %>
                <% [['Novice', "Novice"], ['Intermediate', "Intermediate"], ['Expert', "Expert"], ['Sherpa', "Sherpa"]].each do |c| -%>
                    <%= content_tag(:option, c.first, value: c.last) %>
                <% end %>
            <% end %>
        </div>
 
        <div class="col-sm-3 col-sm-offset-1"> 
            <%= f.label :contact, "Hiker's phone:" %>
            <%= f.text_field :contact %>
        </div>
</div>
<div class="row"> 
        <div class="col-sm-3 col-sm-offset-1">
            <%= f.label :facebook_url, "Hiker's Facebook user name:" %>
            <%= f.text_field :facebook_url, :value =>  "", placeholder: "FB user name"  %>
        </div>

        <div class="col-sm-3 col-sm-offset-1">
            <%= f.label :instagram_url, "Hiker's Instagram user name:" %>                
            <%= f.text_field :instagram_url, :value => "", placeholder: "IG user name" %>
        </div>

        <div class="col-sm-3 col-sm-offset-1">
            <%= f.label :profile_picture, "Hiker's Profile Pic:" %>
            <%= f.file_field :profile_picture %>
            <br/>
            <br/>
        </div>
</div>
<div class="row">    
        <div class="col-sm-12 col-sm-offset-5">
        <%= f.submit "Update Hiker's Info" %>
        </div>
</div>
<% end %>
</section>

app/views/users/index.html.erb
<h1>Hikers</h1>

<ul>
    <% @users.each do |user| %>
        <li>
            <strong><%= user.user_name %></strong> from <%= user.location %> is a <%= user.level %>
        </li>
    <% end %>
</ul>

app/views/users/new.html.erb
<section id="hikes">
<h2 class="text-center">Create your profile!</h2>

<%= form_for(@user) do |f| %>
<div class="row">
        <div class="col-sm-3 col-sm-offset-1">
            <%= f.label :name, "Hiker's name:" %>
            <%= f.text_field :name %>
        </div>

        <div class="col-sm-3 col-sm-offset-1">
            <%= f.label :email, "Hiker's e-mail address:" %>
            <%= f.email_field :email %>
        </div>

        <div class="col-sm-3 col-sm-offset-1">
            <%= f.label :hometown, "Hiker's hometown:" %>
            <%= f.text_field :hometown %>
        </div>
</div>
<div class="row">
        <div class="col-sm-3 col-sm-offset-1">
            <%= f.label :password_digest, "Hiker's password:" %>
            <%= f.password_field :password_digest %>
        </div>
 
        <div class="col-sm-3 col-sm-offset-1">
            <%= f.label :level, "Hiker's ability level:" %>
            <%= f.select(:level) do %>
                <% [['Novice', "Novice"], ['Intermediate', "Intermediate"], ['Expert', "Expert"], ['Sherpa', "Sherpa"]].each do |c| -%>
                    <%= content_tag(:option, c.first, value: c.last) %>
                <% end %>
            <% end %>
        </div>
 
        <div class="col-sm-3 col-sm-offset-1"> 
            <%= f.label :contact, "Hiker's phone:" %>
            <%= f.text_field :contact %>
        </div>
</div>
<div class="row"> 
        <div class="col-sm-3 col-sm-offset-1">
            <%= f.label :facebook_url, "Hiker's Facebook user name:" %>
            <%= f.text_field :facebook_url, :value =>  "", placeholder: "FB user name"  %>
        </div>

        <div class="col-sm-3 col-sm-offset-1">
            <%= f.label :instagram_url, "Hiker's Instagram user name:" %>                
            <%= f.text_field :instagram_url, :value => "", placeholder: "IG user name" %>
        </div>

        <div class="col-sm-3 col-sm-offset-1">
            <%= f.label :profile_picture, "Hiker's Profile Pic:" %>
            <%= f.file_field :profile_picture %>
            <br/>
            <br/>
        </div>
</div>
<div class="row">    
        <div class="col-sm-12 col-sm-offset-5">
        <%= f.submit "Create Hiker's Info" %>
        </div>
</div>
<% end %>
</section>

app/views/users/show.html.erb
<h2 class="text-center">All about <%= link_to @user.name, user_path(@user.id) %>! </h2>
<br/>
<br/>
<div class="row">
    <div id="profile_photo" class="col-sm-4 col-sm-offset-1">
        <%= image_tag @user.profile_picture.url %>
        <p>Experience level: <%= @user.level%>
    </div>

    <div class="col-sm-6 col-sm-offset-1">
        <p>Phone number: <%= @user.contact %></p>
        <p>Current Hometown:  <%= @user.hometown %></p>
        <p>E-mail address: <%= @user.email %></p>
        <p><%= link_to "Facebook", "https://www.facebook.com/#{@user.facebook_url}", target: "_blank" %> </p>
        <p><%= link_to "Instagram", "https://www.instagram.com/#{@user.instagram_url}", target: "_blank" %> </p>
    </div> 
</div>
<div class="row">
    <hr>
</div>

<div class="row text-center">
    <div class="col-sm-4 col-sm-offset-1">
        <p>Hosted Hikes: </p>
            <% if @user.created_hikes.count == 0 %>
            <p>None Yet</p>
        <% else %>
            <% @user.created_hikes.each do |hike| %>
                <ul>
                    <li><%= link_to hike.name, hike_path(hike) %></li>
                </ul>
            <% end %>
        <% end %>
    </div>
    <div class="col-sm-4 col-sm-offset-1">
        <p>Attending Hikes: </p>
        <% if @user.hikes.count == 0 %>
            <p>None Yet</p>
        <% else %>
            <% @user.hikes.each do |hike| %>
                <ul>
                    <li><%= link_to hike.name, hike_path(hike) %></li>
                </ul>
            <% end %>
        <% end %>    
    </div>
</div>

<div id="management">
<h6 class="manage, text-center">Manage your profile!
    <br/>
    <br/>
    <%= link_to "Edit Your Profile", edit_user_path(@user) %>
    <%= link_to "Delete Your Profile", user_path(@user), method: :delete %>
</div>